####### rosetta 

### central
python federatedscope/main.py --cfg icml_yaml/central/rosetta_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp2.lr1.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/central/rosetta_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp2.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/central/rosetta_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp2.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/central/rosetta_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp2.lr3.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/central/rosetta_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp2.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/central/rosetta_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp2.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type emu 


python federatedscope/main.py --cfg icml_yaml/central/rosetta_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp5.lr1.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/central/rosetta_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp5.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/central/rosetta_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp5.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/central/rosetta_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp5.lr3.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/central/rosetta_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp5.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/central/rosetta_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp5.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type emu 


# fedot 
python federatedscope/main.py --cfg icml_yaml/fedot/rosetta_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp2.lr1.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedot/rosetta_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp2.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedot/rosetta_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp2.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedot/rosetta_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp2.lr3.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedot/rosetta_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp2.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedot/rosetta_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp2.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu 


python federatedscope/main.py --cfg icml_yaml/fedot/rosetta_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp5.lr1.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedot/rosetta_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp5.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedot/rosetta_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.rosetta.dp5.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedot/rosetta_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp2.lr3.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedot/rosetta_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp5.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedot/rosetta_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.rosetta.dp5.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu 


# fedbiot 
python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu




python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt2_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu




python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu




python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_code/humanevalx.py --cfg icml_yaml/fedbiot/rosetta/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.rosetta.adpt4_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu
