####### dolly 

### central
python federatedscope/main.py --cfg icml_yaml/central/dolly_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp2.lr1.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp2.lr1.central_full --suite llama.dolly.dp2.lr1.central_full --yaml icml_yaml/central/dolly_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp2.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.dp2.lr1.central_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp2.lr1.central_emu --suite llama.dolly.dp2.lr1.central_emu --yaml icml_yaml/central/dolly_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp2.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.dp2.lr1.central_emu

python federatedscope/main.py --cfg icml_yaml/central/dolly_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp2.lr3.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp2.lr3.central_full --suite llama.dolly.dp2.lr3.central_full --yaml icml_yaml/central/dolly_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp2.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.dp2.lr3.central_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp2.lr1.central --suite llama.dolly.dp2.lr1.central --yaml icml_yaml/central/dolly_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp2.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.dp2.lr3.central_emu


python federatedscope/main.py --cfg icml_yaml/central/dolly_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp5.lr1.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp5.lr1.central_full --suite llama.dolly.dp5.lr1.central_full --yaml icml_yaml/central/dolly_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp5.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.dp5.lr1.central_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp5.lr1.central_emu --suite llama.dolly.dp5.lr1.central_emu --yaml icml_yaml/central/dolly_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp5.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.dp5.lr1.central_emu

python federatedscope/main.py --cfg icml_yaml/central/dolly_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp5.lr3.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp5.lr3.central_full --suite llama.dolly.dp5.lr3.central_full --yaml icml_yaml/central/dolly_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp5.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.dp5.lr3.central_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp5.lr3.central_emu --suite llama.dolly.dp5.lr3.central_emu --yaml icml_yaml/central/dolly_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp5.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.dp5.lr3.central_emu


# fedot 
python federatedscope/main.py --cfg icml_yaml/fedot/dolly_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp2.lr1.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp2.lr1.fedot_full --suite llama.dolly.dp2.lr1.fedot_full --yaml icml_yaml/fedot/dolly_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp2.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.dp2.lr1.fedot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp2.lr1.fedot_emu --suite llama.dolly.dp2.lr1.fedot_emu --yaml icml_yaml/fedot/dolly_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp2.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.dp2.lr1.fedot_emu

python federatedscope/main.py --cfg icml_yaml/fedot/dolly_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp2.lr3.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp2.lr3.fedot_full --suite llama.dolly.dp2.lr3.fedot_full --yaml icml_yaml/fedot/dolly_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp2.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.dp2.lr3.fedot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp2.lr3.fedot_emu --suite llama.dolly.dp2.lr3.fedot_emu --yaml icml_yaml/fedot/dolly_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp2.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.dp2.lr3.fedot_emu


python federatedscope/main.py --cfg icml_yaml/fedot/dolly_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp5.lr1.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp5.lr1.fedot_full --suite llama.dolly.dp5.lr1.fedot_full --yaml icml_yaml/fedot/dolly_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp5.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.dp5.lr1.fedot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp5.lr1.fedot_emu --suite llama.dolly.dp5.lr1.fedot_emu --yaml icml_yaml/fedot/dolly_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.dolly.dp5.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.dp5.lr1.fedot_emu

python federatedscope/main.py --cfg icml_yaml/fedot/dolly_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp5.lr3.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp5.lr3.fedot_full --suite llama.dolly.dp5.lr3.fedot_full --yaml icml_yaml/fedot/dolly_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp5.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.dp5.lr3.fedot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.dp5.lr3.fedot_emu --suite llama.dolly.dp5.lr3.fedot_emu --yaml icml_yaml/fedot/dolly_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.dolly.dp5.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.dp5.lr3.fedot_emu


# fedbiot 
python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr1.eps1.lam1.fedbiot_full --suite llama.dolly.adpt2_dp2.lr1.eps1.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp2.lr1.eps1.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr1.eps1.lam1.fedbiot_emu --suite llama.dolly.adpt2_dp2.lr1.eps1.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp2.lr1.eps1.lam1.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr3.eps1.lam1.fedbiot_full --suite llama.dolly.adpt2_dp2.lr3.eps1.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp2.lr3.eps1.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr3.eps1.lam1.fedbiot_emu --suite llama.dolly.adpt2_dp2.lr3.eps1.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp2.lr3.eps1.lam1.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr1.eps1.lam0.fedbiot_full --suite llama.dolly.adpt2_dp2.lr1.eps1.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp2.lr1.eps1.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr1.eps1.lam0.fedbiot_emu --suite llama.dolly.adpt2_dp2.lr1.eps1.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp2.lr1.eps1.lam0.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr3.eps1.lam0.fedbiot_full --suite llama.dolly.adpt2_dp2.lr3.eps1.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp2.lr3.eps1.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr3.eps1.lam0.fedbiot_emu --suite llama.dolly.adpt2_dp2.lr3.eps1.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp2.lr3.eps1.lam0.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr1.eps0.lam1.fedbiot_full --suite llama.dolly.adpt2_dp2.lr1.eps0.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp2.lr1.eps0.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr1.eps0.lam1.fedbiot_emu --suite llama.dolly.adpt2_dp2.lr1.eps0.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp2.lr1.eps0.lam1.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr3.eps0.lam1.fedbiot_full --suite llama.dolly.adpt2_dp2.lr3.eps0.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp2.lr3.eps0.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr3.eps0.lam1.fedbiot_emu --suite llama.dolly.adpt2_dp2.lr3.eps0.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp2.lr3.eps0.lam1.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr1.eps0.lam0.fedbiot_full --suite llama.dolly.adpt2_dp2.lr1.eps0.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp2.lr1.eps0.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr1.eps0.lam0.fedbiot_emu --suite llama.dolly.adpt2_dp2.lr1.eps0.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp2.lr1.eps0.lam0.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr3.eps0.lam0.fedbiot_full --suite llama.dolly.adpt2_dp2.lr3.eps0.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp2.lr3.eps0.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp2.lr3.eps0.lam0.fedbiot_emu --suite llama.dolly.adpt2_dp2.lr3.eps0.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp2.lr3.eps0.lam0.fedbiot_emu




python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr1.eps1.lam1.fedbiot_full --suite llama.dolly.adpt2_dp5.lr1.eps1.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp5.lr1.eps1.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr1.eps1.lam1.fedbiot_emu --suite llama.dolly.adpt2_dp5.lr1.eps1.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp5.lr1.eps1.lam1.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr3.eps1.lam1.fedbiot_full --suite llama.dolly.adpt2_dp5.lr3.eps1.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp5.lr3.eps1.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr3.eps1.lam1.fedbiot_emu --suite llama.dolly.adpt2_dp5.lr3.eps1.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp5.lr3.eps1.lam1.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr1.eps1.lam0.fedbiot_full --suite llama.dolly.adpt2_dp5.lr1.eps1.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp5.lr1.eps1.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr1.eps1.lam0.fedbiot_emu --suite llama.dolly.adpt2_dp5.lr1.eps1.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp5.lr1.eps1.lam0.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr3.eps1.lam0.fedbiot_full --suite llama.dolly.adpt2_dp5.lr3.eps1.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp5.lr3.eps1.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr3.eps1.lam0.fedbiot_emu --suite llama.dolly.adpt2_dp5.lr3.eps1.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp5.lr3.eps1.lam0.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr1.eps0.lam1.fedbiot_full --suite llama.dolly.adpt2_dp5.lr1.eps0.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp5.lr1.eps0.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr1.eps0.lam1.fedbiot_emu --suite llama.dolly.adpt2_dp5.lr1.eps0.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp5.lr1.eps0.lam1.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr3.eps0.lam1.fedbiot_full --suite llama.dolly.adpt2_dp5.lr3.eps0.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp5.lr3.eps0.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr3.eps0.lam1.fedbiot_emu --suite llama.dolly.adpt2_dp5.lr3.eps0.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp5.lr3.eps0.lam1.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr1.eps0.lam0.fedbiot_full --suite llama.dolly.adpt2_dp5.lr1.eps0.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp5.lr1.eps0.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr1.eps0.lam0.fedbiot_emu --suite llama.dolly.adpt2_dp5.lr1.eps0.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp5.lr1.eps0.lam0.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr3.eps0.lam0.fedbiot_full --suite llama.dolly.adpt2_dp5.lr3.eps0.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt2_dp5.lr3.eps0.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt2_dp5.lr3.eps0.lam0.fedbiot_emu --suite llama.dolly.adpt2_dp5.lr3.eps0.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt2_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt2_dp5.lr3.eps0.lam0.fedbiot_emu




python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr1.eps1.lam1.fedbiot_full --suite llama.dolly.adpt4_dp2.lr1.eps1.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp2.lr1.eps1.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr1.eps1.lam1.fedbiot_emu --suite llama.dolly.adpt4_dp2.lr1.eps1.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp2.lr1.eps1.lam1.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr3.eps1.lam1.fedbiot_full --suite llama.dolly.adpt4_dp2.lr3.eps1.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp2.lr3.eps1.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr3.eps1.lam1.fedbiot_emu --suite llama.dolly.adpt4_dp2.lr3.eps1.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp2.lr3.eps1.lam1.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr1.eps1.lam0.fedbiot_full --suite llama.dolly.adpt4_dp2.lr1.eps1.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp2.lr1.eps1.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr1.eps1.lam0.fedbiot_emu --suite llama.dolly.adpt4_dp2.lr1.eps1.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp2.lr1.eps1.lam0.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr3.eps1.lam0.fedbiot_full --suite llama.dolly.adpt4_dp2.lr3.eps1.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp2.lr3.eps1.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr3.eps1.lam0.fedbiot_emu --suite llama.dolly.adpt4_dp2.lr3.eps1.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp2.lr3.eps1.lam0.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr1.eps0.lam1.fedbiot_full --suite llama.dolly.adpt4_dp2.lr1.eps0.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp2.lr1.eps0.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr1.eps0.lam1.fedbiot_emu --suite llama.dolly.adpt4_dp2.lr1.eps0.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp2.lr1.eps0.lam1.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr3.eps0.lam1.fedbiot_full --suite llama.dolly.adpt4_dp2.lr3.eps0.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp2.lr3.eps0.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr3.eps0.lam1.fedbiot_emu --suite llama.dolly.adpt4_dp2.lr3.eps0.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp2.lr3.eps0.lam1.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr1.eps0.lam0.fedbiot_full --suite llama.dolly.adpt4_dp2.lr1.eps0.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp2.lr1.eps0.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr1.eps0.lam0.fedbiot_emu --suite llama.dolly.adpt4_dp2.lr1.eps0.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp2.lr1.eps0.lam0.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr3.eps0.lam0.fedbiot_full --suite llama.dolly.adpt4_dp2.lr3.eps0.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp2.lr3.eps0.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp2.lr3.eps0.lam0.fedbiot_emu --suite llama.dolly.adpt4_dp2.lr3.eps0.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp2.lr3.eps0.lam0.fedbiot_emu




python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr1.eps1.lam1.fedbiot_full --suite llama.dolly.adpt4_dp5.lr1.eps1.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp5.lr1.eps1.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr1.eps1.lam1.fedbiot_emu --suite llama.dolly.adpt4_dp5.lr1.eps1.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp5.lr1.eps1.lam1.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr3.eps1.lam1.fedbiot_full --suite llama.dolly.adpt4_dp5.lr3.eps1.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp5.lr3.eps1.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr3.eps1.lam1.fedbiot_emu --suite llama.dolly.adpt4_dp5.lr3.eps1.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp5.lr3.eps1.lam1.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr1.eps1.lam0.fedbiot_full --suite llama.dolly.adpt4_dp5.lr1.eps1.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp5.lr1.eps1.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr1.eps1.lam0.fedbiot_emu --suite llama.dolly.adpt4_dp5.lr1.eps1.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp5.lr1.eps1.lam0.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr3.eps1.lam0.fedbiot_full --suite llama.dolly.adpt4_dp5.lr3.eps1.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp5.lr3.eps1.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr3.eps1.lam0.fedbiot_emu --suite llama.dolly.adpt4_dp5.lr3.eps1.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp5.lr3.eps1.lam0.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr1.eps0.lam1.fedbiot_full --suite llama.dolly.adpt4_dp5.lr1.eps0.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp5.lr1.eps0.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr1.eps0.lam1.fedbiot_emu --suite llama.dolly.adpt4_dp5.lr1.eps0.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp5.lr1.eps0.lam1.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr3.eps0.lam1.fedbiot_full --suite llama.dolly.adpt4_dp5.lr3.eps0.lam1.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp5.lr3.eps0.lam1.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr3.eps0.lam1.fedbiot_emu --suite llama.dolly.adpt4_dp5.lr3.eps0.lam1.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp5.lr3.eps0.lam1.fedbiot_emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr1.eps0.lam0.fedbiot_full --suite llama.dolly.adpt4_dp5.lr1.eps0.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp5.lr1.eps0.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr1.eps0.lam0.fedbiot_emu --suite llama.dolly.adpt4_dp5.lr1.eps0.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp5.lr1.eps0.lam0.fedbiot_emu

python federatedscope/main.py --cfg icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr3.eps0.lam0.fedbiot_full --suite llama.dolly.adpt4_dp5.lr3.eps0.lam0.fedbiot_full --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite llama.dolly.adpt4_dp5.lr3.eps0.lam0.fedbiot_full
CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/llama.dolly.adpt4_dp5.lr3.eps0.lam0.fedbiot_emu --suite llama.dolly.adpt4_dp5.lr3.eps0.lam0.fedbiot_emu --yaml icml_yaml/fedbiot/dolly/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.dolly.adpt4_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu ; helm-summarize --suite llama.dolly.adpt4_dp5.lr3.eps0.lam0.fedbiot_emu


CUDA_VISIBLE_DEVICES=0 helm-run --conf-paths federatedscope/llm/eval/eval_for_helm/run_specs_icml.conf --enable-local-huggingface-model meta-llama/Llama-2-7b-hf -m 100 --local -n 1 --skip-completed-runs --local-path icml_dolly/raw_llama2 --suite raw_llama2 --yaml icml_yaml/raw_llama2.yaml device 0 llm.offsite_tuning.eval_type full ; helm-summarize --suite raw_llama2