####### gsm8k 

### central
python federatedscope/main.py --cfg icml_yaml/central/gsm8k_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp2.lr1.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/central/gsm8k_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp2.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/central/gsm8k_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp2.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/central/gsm8k_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp2.lr3.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/central/gsm8k_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp2.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/central/gsm8k_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp2.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type emu 


python federatedscope/main.py --cfg icml_yaml/central/gsm8k_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp5.lr1.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/central/gsm8k_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp5.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/central/gsm8k_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp5.lr1.central.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/central/gsm8k_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp5.lr3.central.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/central/gsm8k_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp5.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/central/gsm8k_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp5.lr3.central.ckpt device 0 llm.offsite_tuning.eval_type emu 


# fedot 
python federatedscope/main.py --cfg icml_yaml/fedot/gsm8k_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp2.lr1.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedot/gsm8k_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp2.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedot/gsm8k_dp2.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp2.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedot/gsm8k_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp2.lr3.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedot/gsm8k_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp2.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedot/gsm8k_dp2.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp2.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu 


python federatedscope/main.py --cfg icml_yaml/fedot/gsm8k_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp5.lr1.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedot/gsm8k_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp5.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedot/gsm8k_dp5.yaml train.optimizer.lr 0.0001 federate.save_to checkpoints/llama.gsm8k.dp5.lr1.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedot/gsm8k_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp5.lr3.fedot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedot/gsm8k_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp5.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedot/gsm8k_dp5.yaml train.optimizer.lr 0.00003 federate.save_to checkpoints/llama.gsm8k.dp5.lr3.fedot.ckpt device 0 llm.offsite_tuning.eval_type emu 


# fedbiot 
python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu




python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt2_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt2_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu




python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp2.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp2.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu




python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps1.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 1.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps1.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 1.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps0.lam1.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu


python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.0001 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr1.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu 

python federatedscope/main.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type full 
CUDA_VISIBLE_DEVICES=0 python federatedscope/llm/eval/eval_for_gsm8k/eval_with_demo.py --cfg icml_yaml/fedbiot/gsm8k/adpt4_dp5.yaml train.optimizer.lr 0.00003 llm.offsite_tuning.emu_align.train.lm_loss_weight 0.0 llm.offsite_tuning.emu_align.train.kd_loss_weight 0.0 federate.save_to checkpoints/llama.gsm8k.adpt4_dp5.lr3.eps0.lam0.fedbiot.ckpt device 0 llm.offsite_tuning.eval_type emu
